INSERT INTO account (email,
                     hashed_password,
                     last_name, first_name,
                     middle_name,
                     phone,
                     count_vacation_days,
                     profession_id,
                     role_id,
                     division_id)
VALUES (@Email,
        @HashedPassword,
        @LastName,
        @FirstName,
        @MiddleName,
        @Phone,
        @CountVacationDays,
        @ProfessionId,
        @RoleId,
        @DivisionId)
RETURNING id,
            email                   AS Email,
            hashed_password         AS HashedPassword,
            last_name               AS LastName,
            first_name              AS FirstName,
            middle_name             AS MiddleName,
            phone                   AS Phone,
            count_vacation_days     AS CountVacationDays,
            profession_id           AS ProfessionId,
            role_id                 AS RoleId,
            division_id             AS DivisionId;