//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanTime.Infrastructure.Repositories.Scripts.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanTime.Infrastructure.Repositories.Scripts.Account.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO account (email, hashed_password, last_name, first_name, middle_name, phone, profession_id, role_id)
        ///VALUES (@Email, @HashedPassword, @LastName, @FirstName, @MiddleName, @Phone, @ProfessionId, @RoleId)
        ///RETURNING id, email, hashed_password, last_name, first_name, middle_name, phone, profession_id, role_id;.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM account WHERE id = @Id;.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS (SELECT 1 FROM account WHERE email = @Email);.
        /// </summary>
        internal static string ExistsByEmail {
            get {
                return ResourceManager.GetString("ExistsByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS (SELECT 1 FROM account WHERE id = @Id);.
        /// </summary>
        internal static string ExistsById {
            get {
                return ResourceManager.GetString("ExistsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id                   AS Id,
        ///       email                AS Email,
        ///       hashed_password      AS HashedPassword,
        ///       last_name            AS LastName,
        ///       first_name           AS FirstName,
        ///       middle_name          AS MiddleName,
        ///       phone                AS Phone,
        ///       profession_id        AS ProfessionId,
        ///       role_id              AS RoleId
        ///FROM account
        ///WHERE email = @Email;.
        /// </summary>
        internal static string GetByEmail {
            get {
                return ResourceManager.GetString("GetByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id                   AS Id,
        ///       email                AS Email,
        ///       hashed_password      AS HashedPassword,
        ///       last_name            AS LastName,
        ///       first_name           AS FirstName,
        ///       middle_name          AS MiddleName,
        ///       phone                AS Phone,
        ///       profession_id        AS ProfessionId,
        ///       role_id              AS RoleId
        ///FROM account
        ///WHERE id = @id;.
        /// </summary>
        internal static string GetById {
            get {
                return ResourceManager.GetString("GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE account
        ///SET email = @Email,
        ///    hashed_password = @HashedPassword,
        ///    last_name = @LastName,
        ///    first_name = @FirstName,
        ///    middle_name = @MiddleName,
        ///    phone = @Phone,
        ///    profession_id = @ProfessionId,
        ///    role_id = @RoleId
        ///WHERE id = @Id;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string GetAll
        {
            get
            {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }

        
    }
}
